import streamlit as st
import pandas as pd
import data_manager as dm
from io import BytesIO
import hashlib
import difflib
import time
import json
from datetime import date
from fpdf import FPDF

st.set_page_config(page_title="Product Check App", layout="wide")

# --- DATA NORMALIZER ---
def normalize_items(items):
    """Ensures all items have the required keys."""
    clean_items = []
    for item in items:
        new_item = item.copy()
        # Ensure numeric types
        try: new_item['qty'] = float(new_item.get('qty', 1))
        except: new_item['qty'] = 1.0
        
        try: new_item['price'] = float(new_item.get('price', 0))
        except: new_item['price'] = 0.0
        
        try: new_item['discount_val'] = float(new_item.get('discount_val', 0))
        except: new_item['discount_val'] = 0.0
        
        if 'discount_type' not in new_item: new_item['discount_type'] = '%'
        if 'desc' not in new_item: new_item['desc'] = ""
        
        clean_items.append(new_item)
    return clean_items

# --- CALLBACKS FOR AUTO-FILL ---
def on_product_select():
    """Called when the search selectbox changes."""
    selected_label = st.session_state.get("q_search_product")
    
    # If a product is selected, find it in the DB and fill inputs
    if selected_label:
        try:
            df = dm.get_all_products_df()
            # Reconstruct the label logic to match
            # (Simplified matching: find row where generated label matches)
            # To be efficient, we'll iterate or use the same logic if cached
            # For simplicity here, we assume the label contains the name and filter
            # A robust way is to re-run the label logic:
            
            # 1. Identify columns again (same as in main block)
            def col_has_data(d, c):
                return not d[c].astype(str).str.strip().eq('').all()
            valid_cols = [c for c in df.columns if col_has_data(df, c)]
            name_col = valid_cols[0]
            for c in valid_cols:
                if 'product' in c.lower() or 'model' in c.lower(): name_col = c; break
            
            # Helper to generate label
            forbidden = ['price', 'cost', 'date', 'category', 'srp', 'msrp']
            def make_lbl(row):
                main = str(row[name_col]) if pd.notnull(row[name_col]) else ""
                parts = [main.strip()]
                for col in valid_cols:
                    if col == name_col: continue
                    if any(k in col.lower() for k in forbidden): continue
                    val = str(row[col]).strip()
                    if val and val.lower() not in ['nan', 'none', '']:
                        if val not in parts: parts.append(val)
                return " | ".join(filter(None, parts))
            
            df['Label'] = df.apply(make_lbl, axis=1)
            
            # Find row
            row = df[df['Label'] == selected_label].iloc[0]
            
            # Extract Details
            name_val = str(row[name_col])
            
            # Price
            price_val = 0.0
            price_cols = [c for c in df.columns if any(x in c.lower() for x in ['price', 'msrp', 'srp', 'cost'])]
            for p_col in price_cols:
                val_clean = str(row[p_col]).replace('A$', '').replace('$', '').replace(',', '').strip()
                try:
                    if val_clean and val_clean.lower() != 'nan':
                        price_val = float(val_clean); break
                except: continue
            
            # Description
            desc_val = ""
            desc_cols = [c for c in df.columns if any(x in c.lower() for x in ['desc', 'spec', 'detail'])]
            if desc_cols:
                desc_val = str(row[desc_cols[0]])
                if desc_val.lower() == 'nan': desc_val = ""

            # Update Session State for Inputs
            st.session_state['input_name'] = name_val
            st.session_state['input_desc'] = desc_val
            st.session_state['input_price'] = price_val
            
        except Exception as e:
            print(f"Error autofilling: {e}")

# --- PDF GENERATOR ---
class QuotePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.cell(80, 10, 'MSI', 0, 0, 'L') 
        self.set_font('Arial', 'B', 16)
        self.cell(110, 10, 'Quote', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by Product Check App - MSI Confidential', 0, 0, 'C')

def create_pdf(quote_row):
    pdf = QuotePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Extract & Normalize
    raw_items = json.loads(quote_row['items_json'])
    items = normalize_items(raw_items)
    
    client_name = quote_row['client_name']
    quote_id = str(quote_row['quote_id'])
    created_at = str(quote_row['created_at'])[:10]
    expire_date = str(quote_row.get('expiration_date', ''))
    
    subtotal_ex_gst = 0
    total_discount = 0
    
    for item in items:
        qty = float(item.get('qty', 0))
        price = float(item.get('price', 0))
        d_val = float(item.get('discount_val', 0))
        d_type = item.get('discount_type', '%')
        
        gross = qty * price
        if d_type == '%': disc_amt = gross * (d_val / 100)
        else: disc_amt = d_val
            
        net_line = gross - disc_amt
        subtotal_ex_gst += net_line
        total_discount += disc_amt

    gst_amount = subtotal_ex_gst * 0.10
    grand_total = subtotal_ex_gst + gst_amount
    
    # --- INFO HEADER ---
    pdf.set_font('Arial', '', 10)
    right_x = 130
    pdf.set_xy(right_x, 20); pdf.cell(30, 6, "Quote ref:", 0, 0); pdf.cell(30, 6, quote_id, 0, 1)
    pdf.set_x(right_x); pdf.cell(30, 6, "Issue date:", 0, 0); pdf.cell(30, 6, created_at, 0, 1)
    pdf.set_x(right_x); pdf.cell(30, 6, "Expires:", 0, 0); pdf.cell(30, 6, expire_date, 0, 1)
    pdf.set_x(right_x); pdf.cell(30, 6, "Currency:", 0, 0); pdf.cell(30, 6, "AUD", 0, 1)
    pdf.ln(10)
    
    # --- SELLER / BUYER ---
    y_start = pdf.get_y()
    pdf.set_font('Arial', 'B', 11); pdf.cell(90, 6, "Seller", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(90, 5, "MSI Australia", 0, 1)
    pdf.cell(90, 5, "Suite 304, Level 3, 63-79 Parramatta Rd", 0, 1)
    pdf.cell(90, 5, "Silverwater, NSW 2128", 0, 1)
    
    pdf.set_xy(110, y_start)
    pdf.set_font('Arial', 'B', 11); pdf.cell(80, 6, "Buyer", 0, 1)
    pdf.set_x(110); pdf.set_font('Arial', '', 10)
    pdf.cell(80, 5, client_name, 0, 1)
    pdf.set_x(110); pdf.cell(80, 5, str(quote_row.get('client_email', '')), 0, 1)
    pdf.ln(15)
    
    # --- LINE ITEMS ---
    pdf.set_font('Arial', 'B', 12); pdf.cell(0, 10, "Line Items", 0, 1)
    pdf.set_font('Arial', 'B', 9); pdf.set_fill_color(245, 245, 245)
    pdf.cell(85, 8, "Item", 1, 0, 'L', True)
    pdf.cell(15, 8, "Qty", 1, 0, 'C', True)
    pdf.cell(25, 8, "Unit Price", 1, 0, 'R', True)
    pdf.cell(30, 8, "Discount", 1, 0, 'R', True)
    pdf.cell(35, 8, "Net Total", 1, 1, 'R', True)
    
    pdf.set_font('Arial', '', 9)
    for item in items:
        name = item.get('name', 'Item')
        if len(name) > 45: name = name[:42] + "..."
        qty = float(item.get('qty', 0))
        price = float(item.get('price', 0))
        d_val = float(item.get('discount_val', 0))
        d_type = item.get('discount_type', '%')
        
        gross = qty * price
        if d_type == '%':
            disc_str = f"{d_val}%"
            disc_amt = gross * (d_val / 100)
        else:
            disc_str = f"${d_val}"
            disc_amt = d_val
        net_total = gross - disc_amt
        
        pdf.cell(85, 8, name, 1, 0, 'L')
        pdf.cell(15, 8, str(int(qty)), 1, 0, 'C')
        pdf.cell(25, 8, f"${price:,.2f}", 1, 0, 'R')
        pdf.cell(30, 8, disc_str, 1, 0, 'R')
        pdf.cell(35, 8, f"${net_total:,.2f}", 1, 1, 'R')
    pdf.ln(5)
    
    # --- SUMMARY ---
    pdf.set_x(120); pdf.cell(35, 6, "Subtotal (Ex GST):", 0, 0, 'R'); pdf.cell(35, 6, f"${subtotal_ex_gst:,.2f}", 0, 1, 'R')
    pdf.set_x(120); pdf.cell(35, 6, "Total Discount:", 0, 0, 'R'); pdf.cell(35, 6, f"-${total_discount:,.2f}", 0, 1, 'R')
    pdf.set_x(120); pdf.cell(35, 6, "GST (10%):", 0, 0, 'R'); pdf.cell(35, 6, f"${gst_amount:,.2f}", 0, 1, 'R')
    pdf.set_x(120); pdf.set_font('Arial', 'B', 10)
    pdf.cell(35, 8, "Grand Total:", 0, 0, 'R'); pdf.cell(35, 8, f"${grand_total:,.2f}", 0, 1, 'R')
    return pdf.output(dest='S').encode('latin-1')

# --- AUTH ---
def hash_pw(p): return hashlib.sha256(str.encode(p)).hexdigest()
def check_login(u, p):
    try: users = dm.get_users()
    except: return False, "DB Error"
    if users.empty: return False, "No users"
    user = users[(users['username'] == u) & (users['password'] == hash_pw(p))]
    return (True, user.iloc[0]['role']) if not user.empty else (False, "Invalid")

if 'logged_in' not in st.session_state: st.session_state['logged_in'] = False
if 'user' not in st.session_state: st.session_state['user'] = ""
if 'quote_items' not in st.session_state: st.session_state['quote_items'] = []

# Initialize inputs in session state if not present
if 'input_name' not in st.session_state: st.session_state['input_name'] = ""
if 'input_desc' not in st.session_state: st.session_state['input_desc'] = ""
if 'input_price' not in st.session_state: st.session_state['input_price'] = 0.0

def login_page():
    st.title("🔐 Login"); u = st.text_input("User"); p = st.text_input("Pass", type="password")
    if st.button("Sign In"):
        s, m = check_login(u, p)
        if s: st.session_state['logged_in'] = True; st.session_state['user'] = u; st.rerun()
        else: st.error(m)

def main_app():
    st.sidebar.title(f"User: {st.session_state['user']}")
    if st.sidebar.button("Logout"): st.session_state['logged_in'] = False; st.rerun()
    menu = st.sidebar.radio("Navigate", ["Product Search & Browse", "Quote Generator", "Upload (Direct)", "Data Update (Direct)"])
    
    # 1. SEARCH
    if menu == "Product Search & Browse":
        st.header("🔎 Search")
        if st.button("Refresh"): dm.get_all_products_df.clear(); st.rerun()
        try: df = dm.get_all_products_df()
        except: df = pd.DataFrame()
        
        tab1, tab2 = st.tabs(["Predictive Search", "Full Browse"])
        with tab1:
            if not df.empty:
                # Search Logic
                def col_ok(d,c): return not d[c].astype(str).str.strip().eq('').all()
                vcols = [c for c in df.columns if col_ok(df, c)]
                if vcols:
                    name_col = vcols[0]
                    for c in vcols: 
                        if 'product' in c.lower() or 'model' in c.lower(): name_col = c; break
                    
                    search_df = df.copy()
                    forbidden = ['price', 'cost', 'date', 'category', 'srp']
                    def mk_lbl(r):
                        m = str(r[name_col]) if pd.notnull(r[name_col]) else ""
                        p = [m.strip()]
                        for c in vcols:
                            if c!=name_col and not any(k in c.lower() for k in forbidden):
                                v = str(r[c]).strip()
                                if v and v.lower() not in ['nan','']: p.append(v)
                        return " | ".join(filter(None, p))
                    
                    search_df['Search_Label'] = search_df.apply(mk_lbl, axis=1)
                    opts = sorted([x for x in search_df['Search_Label'].unique().tolist() if x])
                    
                    c1, c2 = st.columns([8, 1])
                    sel = c1.selectbox("Search", opts, index=None, placeholder="Type...", key="s_main")
                    if c2.button("Clear"): st.session_state["s_main"] = None; st.rerun()
                    
                    st.divider()
                    if sel:
                        res = search_df[search_df['Search_Label'] == sel]
                        for i, r in res.iterrows():
                            with st.expander(f"📦 {r[name_col]}", expanded=True):
                                # Display
                                hidden = ['price','cost','srp','msrp']
                                all_c = res.columns.tolist()
                                price_c = [c for c in all_c if any(k in c.lower() for k in hidden)]
                                public = [c for c in all_c if c not in price_c and c!='Search_Label']
                                for c in public:
                                    v = str(r[c]).strip()
                                    if v and v.lower()!='nan': st.write(f"**{c}:** {r[c]}")
                                if price_c:
                                    st.markdown("---")
                                    if st.toggle("Show Price", key=f"t_{i}"):
                                        cols = st.columns(len(price_c))
                                        for idx, p in enumerate(price_c):
                                            cols[idx].metric(p, r[p])
            else: st.warning("Empty DB")
        
        with tab2:
            cats = dm.get_categories()
            if cats:
                cs = st.selectbox("Category", cats)
                if not df.empty and 'category' in df.columns:
                    cd = df[df['category'] == cs]
                    st.dataframe(cd, use_container_width=True)

    # 2. QUOTE
    elif menu == "Quote Generator":
        st.header("📝 Quotes")
        tab_create, tab_hist = st.tabs(["Create Quote", "History"])
        
        with tab_create:
            try: df = dm.get_all_products_df()
            except: df = pd.DataFrame()
            
            # --- A. UNIFIED ADD ITEM SECTION ---
            st.subheader("1. Add Line Item")
            st.caption("Search for a product to auto-fill details, OR simply type to add a custom item.")
            
            # 1. Search Box (Populates session state inputs)
            if not df.empty:
                # Reuse Search Logic for dropdown
                # ... (Same logic as above to generate clean labels) ...
                def col_ok(d,c): return not d[c].astype(str).str.strip().eq('').all()
                vcols = [c for c in df.columns if col_ok(df, c)]
                if vcols:
                    name_col = vcols[0]
                    for c in vcols: 
                        if 'product' in c.lower() or 'model' in c.lower(): name_col = c; break
                    
                    search_df = df.copy()
                    forbidden = ['price', 'cost', 'date', 'category', 'srp']
                    def mk_lbl(r):
                        m = str(r[name_col]) if pd.notnull(r[name_col]) else ""
                        if m.lower() in ['nan','']: return None
                        p = [m.strip()]
                        for c in vcols:
                            if c!=name_col and not any(k in c.lower() for k in forbidden):
                                v = str(r[c]).strip()
                                if v and v.lower() not in ['nan','']: p.append(v)
                        return " | ".join(filter(None, p))
                    
                    search_df['Label'] = search_df.apply(mk_lbl, axis=1)
                    opts = sorted([x for x in search_df['Label'].unique().tolist() if x])
                    
                    # Search Box with Callback
                    st.selectbox(
                        "Search Database (Optional)", 
                        options=opts, 
                        index=None, 
                        placeholder="Select a product to auto-fill...",
                        key="q_search_product",
                        on_change=on_product_select # Triggers auto-fill
                    )

            # 2. Input Form (Pre-filled by search, but editable)
            with st.container(border=True):
                c1, c2 = st.columns([1, 2])
                # Note: We use keys matching what on_product_select updates
                name_in = c1.text_input("Product Name", key="input_name")
                desc_in = c2.text_input("Description", key="input_desc")
                
                c3, c4, c5, c6 = st.columns(4)
                qty_in = c3.number_input("Qty", min_value=1.0, value=1.0, step=1.0)
                price_in = c4.number_input("Unit Price ($)", value=st.session_state.get('input_price', 0.0), key="input_price")
                disc_val = c5.number_input("Discount", 0.0)
                disc_type = c6.selectbox("Type", ["%", "$"])
                
                if st.button("➕ Add Line Item"):
                    if name_in:
                        # Add to list
                        item = {
                            "name": name_in,
                            "desc": desc_in,
                            "qty": qty_in,
                            "price": price_in,
                            "discount_val": disc_val,
                            "discount_type": disc_type,
                            "total": 0 # Calc later
                        }
                        st.session_state['quote_items'].append(item)
                        # Clear inputs
                        st.session_state['input_name'] = ""
                        st.session_state['input_desc'] = ""
                        st.session_state['input_price'] = 0.0
                        st.session_state['q_search_product'] = None
                        st.rerun()
                    else:
                        st.error("Item Name is required.")

            st.divider()
            
            # --- B. REVIEW TABLE (EDITABLE) ---
            st.subheader("2. Review Items")
            
            if st.session_state['quote_items']:
                # Normalize first to prevent errors
                st.session_state['quote_items'] = normalize_items(st.session_state['quote_items'])
                q_df = pd.DataFrame(st.session_state['quote_items'])
                
                # Config Editable Columns
                edited_df = st.data_editor(
                    q_df,
                    num_rows="dynamic",
                    use_container_width=True,
                    key="editor_quote",
                    column_config={
                        "name": st.column_config.TextColumn("Item Name", required=True),
                        "desc": st.column_config.TextColumn("Description"),
                        "qty": st.column_config.NumberColumn("Qty", min_value=1, required=True),
                        "price": st.column_config.NumberColumn("Unit Price", format="$%.2f", required=True),
                        "discount_val": st.column_config.NumberColumn("Discount", min_value=0.0),
                        "discount_type": st.column_config.SelectboxColumn("Type", options=["%", "$"], required=True),
                        "total": st.column_config.NumberColumn("Net Total", format="$%.2f", disabled=True)
                    }
                )
                
                # Recalculate Totals from Edited Data
                sub_ex = 0; tot_disc = 0; items_save = []
                for index, row in edited_df.iterrows():
                    q = float(row.get('qty', 0)); p = float(row.get('price', 0))
                    d = float(row.get('discount_val', 0)); t = row.get('discount_type', '%')
                    
                    gross = q * p
                    disc = gross * (d/100) if t == '%' else d
                    net = gross - disc
                    
                    sub_ex += net
                    tot_disc += disc
                    
                    # Update Row Data
                    r = row.to_dict()
                    r['total'] = net
                    items_save.append(r)

                gst = sub_ex * 0.10
                grand = sub_ex + gst

                # Display Totals
                m1, m2, m3, m4 = st.columns(4)
                m1.metric("Subtotal (Ex GST)", f"${sub_ex:,.2f}")
                m2.metric("Total Discount", f"${tot_disc:,.2f}")
                m3.metric("GST (10%)", f"${gst:,.2f}")
                m4.metric("Grand Total", f"${grand:,.2f}")
                
                # --- C. SAVE SECTION ---
                st.subheader("3. Client Details & Save")
                c_details, c_actions = st.columns([2, 1])
                
                with c_details:
                    with st.container(border=True):
                        q_client = st.text_input("Client Name", value=st.session_state.get('edit_client', ''))
                        q_email = st.text_input("Email", value=st.session_state.get('edit_email', ''))
                        q_date = st.date_input("Date", date.today())
                        q_expire = st.date_input("Expires", date.today())
                
                with c_actions:
                    st.write("") # Spacing
                    st.write("")
                    if st.button("💾 Save Quote", type="primary", use_container_width=True):
                        if not q_client: st.error("Client Name Required")
                        else:
                            payload = {
                                "client_name": q_client,
                                "client_email": q_email,
                                "total_amount": grand,
                                "expiration_date": str(q_expire),
                                "items": items_save
                            }
                            dm.save_quote(payload, st.session_state['user'])
                            st.success("Quote Saved!")
                            st.session_state['quote_items'] = []
                            st.session_state['input_name'] = ""
                            time.sleep(1); st.rerun()
                    
                    if st.button("Clear All Items", use_container_width=True):
                        st.session_state['quote_items'] = []
                        st.rerun()
            else:
                st.info("No items added yet.")

        # --- HISTORY ---
        with tab_hist:
            st.subheader("📜 Quote History")
            if st.button("Refresh List"): dm.get_quotes.clear(); st.rerun()
            q_hist = dm.get_quotes()
            if not q_hist.empty:
                q_hist = q_hist.sort_values(by="created_at", ascending=False)
                for i, row in q_hist.iterrows():
                    with st.expander(f"{row['created_at']} | {row['client_name']} | ${float(row['total_amount']):,.2f}"):
                        c1, c2, c3 = st.columns(3)
                        try:
                            pdf = create_pdf(row)
                            c1.download_button("📩 PDF", pdf, f"Quote_{row['quote_id']}.pdf", "application/pdf")
                        except: c1.error("PDF Error")
                        
                        if c2.button("✏️ Edit", key=f"e_{row['quote_id']}"):
                            st.session_state['quote_items'] = normalize_items(json.loads(row['items_json']))
                            st.session_state['edit_client'] = row['client_name']
                            st.session_state['edit_email'] = row.get('client_email', '')
                            st.toast("Loaded to Create Tab"); time.sleep(1)
                        
                        if c3.button("🗑️ Delete", key=f"d_{row['quote_id']}"):
                            dm.delete_quote(row['quote_id'], st.session_state['user'])
                            st.rerun()
            else: st.info("No history.")

    # 3. UPLOAD
    elif menu == "Upload (Direct)":
        st.header("📂 Upload"); c1, c2 = st.columns(2)
        with c1: 
            cats = dm.get_categories()
            c_sel = st.selectbox("Category", cats if cats else ["Default"])
        with c2:
            new_c = st.text_input("New Category")
            if st.button("Add"): 
                if new_c: dm.add_category(new_c, st.session_state['user']); st.rerun()
        
        up = st.file_uploader("File", accept_multiple_files=True)
        hh = st.checkbox("Headers?", True)
        if up:
            for f in up:
                if st.button(f"Save {f.name}"):
                    try:
                        df = pd.read_csv(f, header=0 if hh else None) if f.name.endswith('csv') else pd.read_excel(f, header=0 if hh else None)
                        dm.save_products_dynamic(df.dropna(how='all'), c_sel, st.session_state['user'])
                        st.success("Saved!"); time.sleep(1); st.rerun()
                    except Exception as e: st.error(str(e))

    # 4. UPDATE
    elif menu == "Data Update (Direct)":
        st.header("🔄 Update"); cats = dm.get_categories(); c_sel = st.selectbox("Category", cats)
        up = st.file_uploader("New File"); hh = st.checkbox("Headers?", True, key="uph")
        if up:
            df = pd.read_csv(up, header=0 if hh else None) if up.name.endswith('csv') else pd.read_excel(up, header=0 if hh else None)
            st.write(df.head(3))
            k = st.selectbox("ID Column", list(df.columns))
            if st.button("Update"):
                r = dm.update_products_dynamic(df, c_sel, st.session_state['user'], k)
                st.success(f"Updated. New: {r['new']}, EOL: {r['eol']}")

if st.session_state['logged_in']: main_app()
else: login_page()
